version: 2
updates:
  - package-ecosystem: "composer"
    commit-message:
      prefix: "chore(deps-composer):"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"
  - package-ecosystem: "npm"
    commit-message:
      prefix: "chore(deps-npm):"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "chore(deps-github-actions):"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"

