services:
  donezo.ws:
    build:
      context: './dev'
      dockerfile: Dockerfile
    image: 'akyrey/donezo:dev'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:5173'
      - '${REVERB_PORT:-8080}:8080'
    volumes:
      - '.:/app'
      - 'donezo-home:/home/developer'
    networks:
      - donezo.dev
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_started
  pgsql:
    image: 'postgres:18'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-password}'
      POSTGRES_DB: '${DB_DATABASE:-donezo}'
      POSTGRES_USER: '${DB_USERNAME:-donezo}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'donezo-pgsql:/var/lib/postgresql'
    networks:
      - donezo.dev
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE:-donezo}'
        - '-U'
        - '${DB_USERNAME:-donezo}'
      retries: 3
      timeout: 5s
  redis:
    image: 'valkey/valkey:9-alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'donezo-redis:/data'
    networks:
      - donezo.dev
    healthcheck:
      test: "valkey-cli ping"
      start_period: 2s
      interval: 1s
      timeout: 5s
      retries: 55
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - donezo.dev

networks:
  donezo.dev:
    driver: bridge

volumes:
  donezo-home:
    driver: local
  donezo-pgsql:
    driver: local
  donezo-redis:
    driver: local
