[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
minfds=10000

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_DEV_USER)s
environment=HOME="/home/%(ENV_DEV_USER)s",USER="%(ENV_DEV_USER)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:pnpm]
command=pnpm run dev
directory=%(ENV_WORKDIR)s
user=%(ENV_DEV_USER)s
environment=HOME="/home/%(ENV_DEV_USER)s",USER="%(ENV_DEV_USER)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:reverb]
command=php %(ENV_WORKDIR)s/artisan reverb:start --host="0.0.0.0" --port=8080 --no-interaction --no-ansi --verbose
user=%(ENV_DEV_USER)s
environment=HOME="/home/%(ENV_DEV_USER)s",USER="%(ENV_DEV_USER)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
