# Directories
.git/
.idea/
dev/
node_modules/
vendor/
public/
!public/index.php
!public/favicon.png
!public/robots.txt
!public/sw.js
!public/manifest.webmanifest
!public/icons/
!public/splash/
storage/*

# Files
.*
!.env.production
