# Directories
.git/
.idea/
dev/
node_modules/
vendor/
public/
!public/index.php
!public/favicon.ico
!public/robots.txt
!public/sw.js
!public/manifest.webmanifest
!public/images/
storage/*

# Files
.*
!.env.production
